--- 

- name: Create Nexus User
  user:
    name: nexus
    group: nexus
    password: '$6$s6DGXsPl8f$SPUJ8/CEuFHNQKKfYP.5.Hf.Qsd0/Z9yc63rr/U2EckkWf0b9s5zw6WxkJdZ8TO7HTFWjYNWirLewVP7RYBZC1' 
    # Password is "nexus" generated through "mkpasswd --method=sha-512". Check if '' is required
    createhome: yes 
    #createhome is optional
    home: /home/nexus
    

#SET AUGEAS  
- name: Modify Sudoers file
    
- name: Download Nexus Archive 
  copy:
    src: nexus-{{ nexus_version }}-bundle.tar.gz
    dest: {{ nexus_home }}
    owner: root
    mode: 0755
    
- name: Download Nexus Init Script and Wrapper Conf file from Templates
  template:
    src: "{{ item.src }}"
    dest: "{{ nexus_home }}/bin/{{ item.dest }}"
    mode: 0755
  with_items:
    - { src: 'nexus.j2', dest: 'nexus' }
    - { src: 'wrapper.conf.j2', dest: 'jsw/conf/wrapper.conf' }

- name: Set Nexus Environment Variables
  copy:
    content: 'export NEXUS_HOME={{ nexus_home }}\nexport PATH=\$PATH:\$NEXUS_HOME/bin\nexport NEXUS_OPTS=\"-Xmx512m -Xms512m\"'
    dest: {{ nexus_environment_variable_file }}
    mode: 0755
    
- name: Start Nexus Service
  command: /etc/init.d/nexus start

- name: Create Essential Nexus Directories
  file:
    path: "/usr/local/{{ item.0 }}/{{ item.1 }}"
    state: directory
    owner: nexus
    group: nexus
  with_nested:
    - ['sonatype-work']
    - ['nexus', 'nexus/conf']

- name: Download Nexus Properties file and Conf XML file from Templates 
  template:
    src: "{ item.src }}"
    dest: "usr/local/{{ item.dest }}"
    owner: nexus
    group: nexus
  with_items:
    - { src: 'nexus.properties.j2', dest: 'nexus/conf/nexus.properties' }
    - { src: 'conf.xml.j2', dest: 'sonatype-work/nexus/conf/nexus.xml' }
        
- name: Manage Nexus Service
  service: 
    name: nexus
    state: started
    enabled: yes

    

