---

- name: Create Bower Directory
  file: 
    path: {{ bower_home }}
    state: directory
    mode: 0644
    
- name: Download Bower Package
  copy: 
    src: {{ item }} 
    dest: {{ bower_home }}
  with_items:
    - bower.npmbox 
    - install_bower.sh    
        
- name: Install Bower
  command: bash {{ bower_home }}/install_bower.sh 
  
