---

- name: Download Artifactory Package
  copy:
    src: jfrog-artifactory-oss-{{ artifactory_version }}.zip
    dest: /opt
    
- name: Extract Artifactory Archive
  unarchive:
    src: /opt/jfrog-artifactory-oss-{{ artifactory_version }}.zip
    dest: /usr/local
    remote_src: yes
# Check if this works for "zip" package 

- name: Set Artifactory Home
  file:
    src: /usr/local/artifactory-oss-{{ artifactory_version }}
    dest: {{ artifactory_home }}
    state: link
    
- name: Tomcat Server Config File for Artifactory
  template:
    src: server.xml.j2
    dest: {{ artifactory_home }}/tomcat/conf/server.xml
    mode: 0644
    
- name: Set Artifactory Service File
  file:
    src: {{ artifactory_home }}/bin/installService.sh
    dest: /etc/init.d/artifactory
    mode: 0755
    
- name: Start Tomcat Service
  command: {{ artifactory_home }}/tomcat/bin/catalina.sh start
  
- name: Manage Artifactory Service
  service:
    name: artifactory
    state: started
    enable: yes
