---

- name: Download Java Archive
  copy:
    src: {{ java_archive }}
    dest: /opt

- name: Extract Java Archive
  unarchive:
    src: /opt/{{ java_archive }}
    dest: /usr/lib/jvm
    remote_src: yes

- name: Install Java
  command: /usr/bin/update-alternatives --install /usr/bin/java java {{ java_dir }}/jre/bin/java 1

- name: Set Java
  command: /usr/bin/update-alternatives --set java {{ java_dir }}/jre/bin/java

- name: Set Java Environment Variables
  copy:
    src: set_java_home.sh
    dest: /etc/profile.d
    mode: 0755

