---

- name: Install Jenkins Package Key
  commmand: /usr/bin/wget -O /etc/yum.repos.d/jenkins.repo {{ jenkins_repo_url }} | /bin/rpm --import {{ jenkins_repo_key }}
  
- name: Install Jenkins
  apt:
    name: jenkins={{ jenkins_version }}
    state: present
    force: yes
    
- name: Download Jenkins Essential files
  copy:
    src: {{ item }}
    dest: {{ jenkins_home }}
    owner: jenkins
    group: jenkins
    mode: 0755
  with_items:
    - config.xml
    - hudson.model.UpdateCenter.xml
    - hudson.tasks.Maven.xml
    - nodeMonitors.xml
    
- name: Create Jenkins Essential Directories
  copy: 
    src: "{{ item.src }}"
    dest: "{{ jenkins_home }}/{{ item.dest }}"
    owner: jenkins
    group: jenkins
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'users', dest: 'users', mode: '0755' }
    - { src: 'secrets', dest: 'secrets', mode: '0700' } 
    - { src: 'plugins', dest: 'plugins', mode: '0755' }

    
- name: Set Jenkins Environment Variables
  copy:
    content: 'export JENKINS_HOME={{ jenkins_home }}\nexport PATH=\$PATH:\$JENKINS_HOME'
    dest: {{ jenkins_environment_variable_file }}
    mode: 0755

- name: Manage Jenkins Service
  service:
    name: jenkins
    state: started
    enabled: yes
    

    
