---

- name: Download GIT installation repo
  copy:
    content: '[WandiscoGIT]\nname=Wandisco GIT Repo\nbaseurl=http://opensource.wandisco.com/centos/\$releasever/git/\$basearch/\nenabled=1\ngpgcheck=0'
    dest: /etc/yum.repos.d/wandisco-git.repo

- name: Install GIT
  apt:
    name: git={{ git_version }}
    state: present
    force: yes

- name: Create GIT environment variables
  copy:
    content: 'export GIT_HOME=/usr/bin\nexport PATH=\$PATH:\$GIT_HOME'
    dest: {{ git_environment_variable_file }}
    mode: 0755
