---

- name: Install Postfix
  apt:
    name: postfix={{ postfix_version }}
    state: present
    force: yes
    
- name: Manage Postfix Service
  service:
    name: postfix
    state: started
    enabled: yes
    
